### ISSUE TITLE
GamePad!?

### ISSUE THREAD

**Issue by sa9St** [Montaser1998/ConsoleApp2#1]
hello montaser,

is there any way that we can control GamePad games in palringo ? for example : (simon says bot . or quiz bot..etc)

**Comment by Montaser1998** [comment]
Yes can you but for palringo app .. I had work so I did not develop it .. I will give you a document explaining the addition of palringo on c# 

Document : http://docs.dontpanicitscool.org/palringo/

**Comment by Montaser1998** [comment]
The games that can be played are Time .. Typing .. Calculate but I could not develop it to play better in Time and calculate

**Comment by sa9St** [comment]
i agree but i saw people work , they managed somehow to get the output from GamePad games and they send the input for it , there's one guy who can get all achivment for [Match Maker ,Darts Career total] within 15 min. Thats why i asked you :D
