### ISSUE TITLE
calc solving

### ISSUE THREAD

**Issue by sa9St** [Montaser1998/ConsoleApp2#2]
hey montaser

i found a way to solve calc by using method called DataTable,
that may help you , 
im trying to work with what you told me about the app so i can control GamePad but its still hard work 👍 

شكرا لك على اية حال اخي <3

**Comment by Montaser1998** [comment]
شو اسمك في بالرينجو ؟ اذا بتحكي عربي ريحني انقلش ما اعرف اجاوب 😅😂

**Comment by sa9St** [comment]
ضيفني على العضويه هذي
88188
